class IndicatorConfig:
    MA_PERIOD_SHORT = 50
    MA_PERIOD_LONG = 200

    ADX_TIMEPERIOD = 14
    ADXR_TIMEPERIOD = 14
    AROONOSC_TIMEPERIOD = 14
    DX_TIMEPERIOD = 14
    TRIX_TIMEPERIOD = 14

    STOCH_FASTK_PERIOD = 5
    STOCH_SLOWK_PERIOD = 3
    STOCH_SLOWK_MATYPE = 0
    STOCH_SLOWD_PERIOD = 3
    STOCH_SLOWD_MATYPE = 0

    ULTOSC_TIMEPERIOD1 = 7
    ULTOSC_TIMEPERIOD2 = 14
    ULTOSC_TIMEPERIOD3 = 28

    MACD_FAST_PERIOD = 12
    MACD_SLOW_PERIOD = 26
    MACD_SIGNAL_PERIOD = 9

    BBANDS_TIMEPERIOD = 5
    BBANDS_NBDEVUP = 2
    BBANDS_NBDEVDN = 2
    BBANDS_MATYPE = 0

    PPO_FAST_PERIOD = 12
    PPO_SLOW_PERIOD = 26
