class TradingConfig:
    CASH = 10000
    MACD_FAST = 12
    MACD_SLOW = 26
    MACD_SIGNAL = 9
    ATR_PERIOD = 14
    ATR_DISTANCE = 2.0
    ORDER_PERCENTAGE = 1.0

    BOLLINGER_PERIOD = 14
    BOLLINGER_DEVFACTOR_3 = 3.0
    BOLLINGER_DEVFACTOR_2 = 2.0
    ADX_THRESHOLD = 40

    LOOKBACK_YEARS = 3
